from node import Node

arad = Node('arad')
sibia = Node('sibia')
zerind = Node('zerind')
oradea = Node('oradea')
vilcea = Node('vilcea')
fagaras = Node('fagaras')
pitesti = Node('pitesti')
craiova = Node('craiova')
drobeta = Node('drobeta')
mehadia = Node('mehadia')
lugoj = Node('lugoj')
timisoara = Node('timisoara')
bucharest = Node('bucharest')


arad.append_child(sibia, 140)
arad.append_child(zerind, 75)
arad.append_child(timisoara, 80)
timisoara.append_child(lugoj, 110)
lugoj.append_child(mehadia, 70)
mehadia.append_child(drobeta, 50)
drobeta.append_child(craiova, 10)
zerind.append_child(oradea, 71)
oradea.append_child(sibia, 151)
sibia.append_child(fagaras, 99)
fagaras.append_child(bucharest, 211)
sibia.append_child(vilcea, 80)
vilcea.append_child(pitesti, 70)
craiova.append_child(vilcea, 60)
pitesti.append_child(bucharest, 101)
